name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Configuração do Node
      uses: actions/setup-node@v1
      with:
        node-version: '14'
    - name: Instalação de dependências
      run: npm install
    - name: Build
      run: npm run build

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Configuração do Node
      uses: actions/setup-node@v1
      with:
        node-version: '14'
    - name: Instalação de dependências
      run: npm install
    - name: Testes
      run: npm test

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Configuração do ambiente Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Executando script Python
      run: python ./src/hello_world.py
